from pathlib import Path
import pandas as pd
from typing import Dict, Set


# =====================================
# Workflow config items
configfile: "config/config.yaml"


GB = 1_024
containers: Dict[str, str] = config["containers"]
workflow_dir = Path("workflow").resolve()
scripts_dir = workflow_dir / "scripts"
rules_dir = workflow_dir / "rules"
envs_dir = workflow_dir / "env"
logs_dir = Path("logs/rules").resolve()
data_dir = Path("data").resolve()
results = Path("results").resolve()
transcriptome_url = Path(config["transcriptome_ref"]).resolve()
# =====================================
targets: Set[Path] = set()


rule all:
    input:
        targets,
