from pathlib import Path
import pandas as pd
from typing import Dict, Set


# =====================================
# Workflow config items
configfile: "config/config.yaml"


GB = 1_024
CTRL = ""#todo get control sample name from samplesheet
TESTS = ""#todo get test sample names into list
containers: Dict[str, str] = config["containers"]
GUPPY_VERSION = containers["guppy"].split(":")[-1]
workflow_dir = Path("workflow").resolve()
scripts_dir = workflow_dir / "scripts"
rules_dir = workflow_dir / "rules"
envs_dir = workflow_dir / "env"
logs_dir = Path("logs/rules").resolve()
data_dir = Path("data").resolve()
results = Path("results").resolve()
fast5_dir = Path(config["fast5_dir"]).resolve()
transcriptome_url = Path(config["transcriptome_ref"]).resolve()
# =====================================
targets: Set[Path] = set()



rule all:
    input:
        targets,
